### ISSUE TITLE
Disable PhantomJS Cookies

### ISSUE THREAD

**Issue by SeanHub** [brenden/node-webshot#103]
Hi, as far as I can tell there are no options to disable cookies using the command line PhantomJS options [http://phantomjs.org/api/command-line.html](http://phantomjs.org/api/command-line.html)

Many websites in the European Union require the use of cookies to be authorised. As such, when taking a screenshot, many websites display a banner asking the user if they want to allow the use of cookies. Disabling cookies prevents the banner from showing which makes for a nicer screenshot.

Can cookies be disabled in WebShot?

**Comment by brenden** [comment]
Makes sense, I've just added the ability to disable them in 0.16.0. Use {cookies: null} in the options argument.
