### ISSUE TITLE
Callbacks.js not working

### ISSUE THREAD

**Issue by thiagupct** [brenden/node-webshot#104]
when running the file am getting the error like
```javascript
PhantomJS exited with return value 1
```
Please advice. Thanks

**Comment by codynegri** [comment]
Are you still having issues with this @thiagupct or did you find a solution?

**Comment by thiagupct** [comment]
@codynegri Found no solutions, switched to [Pageres](https://github.com/sindresorhus/pageres)

**Comment by brenden** [comment]
This was caused by this issue: http://stackoverflow.com/questions/24473169/phantomjs-certain-pages-failing-to-open

The demo is now working in 0.16.0.
