### ISSUE TITLE
customCSS option not working

### ISSUE THREAD

**Issue by Biggsen** [brenden/node-webshot#119]
Doesn't look like the option of customCSS is working. I've looked through all the code and found no mention of it. Is it enabled?

**Comment by jasetom** [comment]
It is working, but the problem I've encountered was me writing css in wrong format. If you want to apply customCSS to your page before webshoting it it was to be written in one line and passed as a parameter in webshot function. Example:

var options = {
  siteType: 'html',
  shotSize: {width: 1400, height: 600},
  defaultWhiteBackground: true,
  customCSS: 'body{font:10px sans-serif;} .axis path,.axis line{fill: none; stroke:#000;}'
};

//Using webshot
webshot(svgsrc,'Graphi3.png',options,function(err) {
//saves image
});

**Comment by brenden** [comment]
Hey thanks @jasetom for answering that. Just for my understanding, what's the format that wasn't working for you? Newlines in the customCSS string?

**Comment by jasetom** [comment]
@brenden yes I believe that was the problem

**Comment by brenden** [comment]
Hmmm just tried with newlines and it worked fine for me. I'll close this ticket for now, though feel free to reopen if you have a sample showing the error.
