### ISSUE TITLE
Specify path where to save image/ retrieve saved images path

### ISSUE THREAD

**Issue by jasetom** [brenden/node-webshot#120]
Its not really and issue with a library itself, but I didn't know where I could ask this question as I couldn't find the answer anywhere else. Is there a way to specify the path that the image will get saved to and also return path after the image is saved as I want to save my image to amazon S3 and then retrieve that url to be displayed in slack.
Any help would be appreciated, thanks

**Comment by CristianaPereira** [comment]
I'm having the same problem.

**Comment by Raincle** [comment]
I'm having the same problem, too.

**Comment by stevenho0811** [comment]
Same here.
