### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by kucukkanat** [brenden/node-webshot#121]
When I take a shot as pdf my images are broken and split into two pages, like 1/5 of the image remains in the previous page.
What can I do not to break components in html while rendering as PDF?

I go like : 

```javascript
webshot(URL_To_Shoot,FilePath_To_Save,{
shotSize:{ width: 'all', height: 'all' },
paperSize:{format:'A4',orientation:'portrait'}
},function(err){
...
})

```

**Comment by brenden** [comment]
Can you post an example URL that shows the problem?

**Comment by kucukkanat** [comment]
![image](https://cloud.githubusercontent.com/assets/914316/10570240/c6c82c4e-7639-11e5-8821-376ed12f06b8.png)

Sometimes the comboboxes or input fields are even broken into half

**Comment by kucukkanat** [comment]
![screen shot 2015-10-19 at 08 16 30](https://cloud.githubusercontent.com/assets/914316/10570245/e462a496-7639-11e5-818c-45f264fed18a.png)

**Comment by brenden** [comment]
OK I see. Looks like this is an open issue in PhantomJS and it will have to be fixed there: https://github.com/ariya/phantomjs/issues/10551

You might be able to solve the problem in some cases by just modifying the page's stylesheet. This thread suggests a few approaches that could work: https://github.com/ariya/phantomjs/issues/10638
