### ISSUE TITLE
siteType: 'html' does not resolve any dependancy

### ISSUE THREAD

**Issue by agustik** [brenden/node-webshot#140]
I'm trying to render html from variable to PNG image. The HTML is created with some dynamic and I use Bootstrap css.

If I use the siteType: 'html' or 'file' it does not resolve the dependancy. But if i create a http server and serve the file over HTTP it works.

```
webshot(html, 'image.png', { siteType : 'html' }, function(err) {
  console.log('Created image.png', err)
});
```

**Comment by agustik** [comment]
Solved

npm install phantomjs2 

Add phantomPath: require('phantomjs2').path to options

var options = {
phantomPath: require('phantomjs2').path
}

**Comment by mutil** [comment]
Solution posted by @agustik is not working for me, produces same output.
