### ISSUE TITLE
full page screenshot

### ISSUE THREAD

**Issue by ImanMh** [brenden/node-webshot#159]
Is seems like it's impossible to take a full page screenshot instead of specifying height. How can I tell webshot to take a screen shot of a url with a window ex 900px width and full height?

**Comment by nahanil** [comment]
Should be something like
`var options = {
  shotSize: {
    height: 'all'
  }
};`

https://github.com/brenden/node-webshot#examples

**Comment by revelt** [comment]
@ImanMh can we close this issue, or is it not working for you?

**Comment by ImanMh** [comment]
@revelt Thanks for the response I forgot to send a reply here. It  works.

**Comment by revelt** [comment]
cheers!
