### ISSUE TITLE
zoomFactor option

### ISSUE THREAD

**Issue by juanbenitopr** [brenden/node-webshot#186]
Hi!

I'm trying to use zoomFactor option, the next way:
`
webshot 'google.com', 'imagen/google.jpg',{screenSize:{height:1000,width:1000}, zoomFactor:0.3, quality:30} ,(err) ->`

but I can't get anything, it is always the same image, it just change if I modify the screenSize property. Some idea?

I need get the completely image but I can't raise the size file

PD: The code is CoffeeScript

Thanks!

**Comment by demerzel3** [comment]
Can you try using my fix? https://github.com/brenden/node-webshot/pull/191
