### ISSUE TITLE
Running on AWS Lambda

### ISSUE THREAD

**Issue by CBox** [brenden/node-webshot#223]
Hey,

I'm trying to run it on AWS Lambda and getting this error:
Error: spawn /var/task/node_modules/phantomjs-prebuilt/lib/phantom\bin\phantomjs.exe ENOENT

My local machine is Win but why it's trying to use the exe? Can I change the path?

Thanks.

**Comment by CBox** [comment]
I've found that I need to run it with:
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2

How I can change the path for the PhantomJS?

**Comment by CBox** [comment]
Found this on the options: "phantomPath" thanks!

**Comment by akjaiswal1611** [comment]
can you share the snippet and file structure of how u used websnapshot on lambda
