### ISSUE TITLE
Webshot from URL on Heroku not working

### ISSUE THREAD

**Issue by facultymatt** [brenden/node-webshot#25]
Hello, I've tried with no success to get webshot to work on Heroku. Oddly, it works fine locally and when running `foreman start` (which should emulate Heroku.) Here are some more details: 
- Works fine running foreman
- Tried a number or different output methods, ie: streaming, writing to file, DL the file. 
- On Heroku, sometimes webshot fails, and I get an error. Other times it appears to work fine... but no image is saved. 
- I've tried pointing to multiple URLs which all fail on Heroku. 

I've used a few variations of your examples and code I've found online. I can post code samples here if needed, but maybe you have more insight into Heroku? 

I've seen mention online to a custom buildpack, is this needed? 

Thanks,
-Matt

**Comment by ksprashu** [comment]
If anyone is still watching this issue, can you help me with where heroku stores the screenshots taken via webshots?
How do I access these files then?

**Comment by fivepointseven** [comment]
@ksprashu did you figure it out?
My app won't even save screenshot when deployed to Heroku. Everything is fine using Foreman though.

**Comment by ismyrnow** [comment]
@ksprashu @fivepointseven: It may be that heroku doesn't allow writing files to the filesystem. However, you can put the contents into a database, or send as a response to a web request. I am actually putting the image into a pdf.

If your second argument is an options object, and your callback has two arguments, the second callback argument will be a stream which you can work with.

Here is an example of converting the stream into a buffer:

```javascript
webshot(url, options, function (err, renderStream) {
  var imageBuffers = [];

  renderStream.on('data', function (data) {
    imageBuffers.push(data);
  });

  renderStream.on('end', function () {
    var imageBuffer = Buffer.concat(imageBuffers);

    // Do something with your buffer (imageBuffer);
  });
});
```

**Comment by ksprashu** [comment]
@fivepointseven @ismyrnow My calls were not failing (as per the logs) but there was no way I could retrieve them back from Heroku.

What I did then was to use the dropbox APIs and just save the image directly to dropbox. Then I could sync and retrieve them later.
