### ISSUE TITLE
Return base64 image returns half image

### ISSUE THREAD

**Issue by aloncarmel** [brenden/node-webshot#41]
Hey im trying to return a base64 image but im finding it hard, when i write the file to disk its fine. when i return base64 it returns half an image.

  var options = {
    screenSize: {
    width: 1280
  , height: 768
   }
   , streamType: 'png'
   , shotSize: {
       width: 1280
     , height: 768
    }
}

webshot(url, options,function(err, renderStream) {

```
renderStream.on('data', function(data) {

res.send(data.toString('binary'));

});
```

});

returns a valid base64 just a tiny portion of the screen. Really weird.

any ideas?

**Comment by shabith** [comment]
with **Node.js ~>0.8** you can use Buffer.concat as below:
```javascript

webshot(url, options,function(err, renderStream) {
   var bufArr = [];
   renderStream.on('data', function(data) {
      bufArr.push(data);
   });

   renderStream.on('end', function() {
      var buf = Buffer.concat(bufArr);
      res.send(buf.toString('binary'));
   });
});


```
