### ISSUE TITLE
Integrate with resize and crop lib

### ISSUE THREAD

**Issue by evilebottnawi** [brenden/node-webshot#44]
Example - https://github.com/madhums/node-imager
Create options "thumbnail" and "thumbnailCrop" with params width, height and crop(true/false) for resize and/or crop image.

**Comment by EOdOW** [comment]
:+1:

**Comment by 4e1ovek** [comment]
:+1:

**Comment by curran** [comment]
For generating thumbnails, if you can get the content into an iFrame, you can scale the iFrame with the following styles:

``` css
transform: scale(0.25);
transform-origin: 0 0;
-webkit-transform: scale(0.25);
-webkit-transform-origin: 0 0;
```

I ended up using this in conjunction with webshot for generating thumbnails by matching the screen size option with the scaled size.
